export const HOP_CHANNEL_ID = 'raycast-browser'
export const HOP_CHANNEL_EVENT = 'commands'
export const HOP_CHANNEL_RESPONSE_EVENT = 'responses'
export const HOP_CHANNEL_TOKEN = ''
export const HOP_PROJECT_ID = ''
export const HOP_PROJECT_TOKEN = ''